### ISSUE TITLE
Disable direct changes to master branch

### ISSUE THREAD

**Issue by BenRGH** [DoctorDib/BikeTheft#4]
I think the standard protocol is we make a branch for any changes and then once the pull request is approved by another dev it can go into the master, therefore we **disable** pushing changes directly to the master branch that might break something without going through PR **first**.

**Comment by DoctorDib** [comment]
If you're referring to what I just did with #1 - there would be no point in creating a PR for the initial file as no code is or would have been affected. I do agree we should always work on branches however since this is a really small project, I don't believe it needs to be checked by another dev. If the project was bigger (company level) then I would 100% agree.

**Comment by BenRGH** [comment]
I'm suggesting it because we'll almost definitely have a pipeline of some sort (CI/CD) so if someone _accidentally_ breaks master then we're screwed

**Comment by Yakitrak** [comment]
We should have separate branches for our separate tasks perhaps but other than, we should definitely have a dev branch and to pull to production branch, it needs to be approved / CI/CD pipeline.

**Comment by BenRGH** [comment]
Relevant how-to https://docs.github.com/en/github/administering-a-repository/enabling-branch-restrictions

**Comment by BenRGH** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Disable direct changes to master branch](https://trello.com/c/5p08LP8V/12-disable-direct-changes-to-master-branch)

**Comment by DoctorDib** [comment]
Unfortunately client git hooks only work with git and not he clients. We have create a release branch to have as the production version where we ONLY commit **working** code.
